### ISSUE TITLE
New version of oereb_client?

### ISSUE THREAD

**Issue by jwkaltz** [openoereb/oereb_client#101]
Hi @kdeininger ,
can you publish a new version of the oereb_client?
We wish to try it out at FL, with Peter.

**Comment by jwkaltz** [comment]
@kdeininger thanks for the new version, unfortunately it is not working, there is an error upon loading the code. We tried it on the FL server, and I can reproduce it in a local development environment. 

I attach a screenshot of my browser console. The error appears right away when loading the page:
![Screenshot from 2021-02-25 06-41-52](https://user-images.githubusercontent.com/9261252/109108887-a5e22c80-7734-11eb-8237-e7bfb073b795.png)

Do you have an idea what is wrong? I don't know angular, but of course I have several colleagues here who can assist if the error cause is not clear to you.

**Comment by kdeininger** [comment]
There has been a change in the artifacts upload/download action. It should be fixed now. Could you please try the latest dev package?

https://test.pypi.org/project/oereb-client/1.3.8.dev202103011318/

**Comment by jwkaltz** [comment]
> Could you please try the latest dev package?

Yes thanks, see my PR comment there.
