### ISSUE TITLE
Use pyaml-env to parse the configuration

### ISSUE THREAD

**Issue by kdeininger** [openoereb/oereb_client#326]
Use [pyaml-env](https://pypi.org/project/pyaml-env/) to parse the configuration and set default values.

**Comment by jwkaltz** [comment]
Hi @kdeininger , will this allow to use environment variables directly in the oereb_client.yml? Or is this for another need?

For reference, my candidates: SERVICE_URL, AVAILABILITY_URL, SEARCH_URL

**Comment by kdeininger** [comment]
> Hi @kdeininger , will this allow to use environment variables directly in the oereb_client.yml? Or is this for another need?
> 
> For reference, my candidates: SERVICE_URL, AVAILABILITY_URL, SEARCH_URL

Yes, you can use environment variables directly in your configuration.

For example:

```yaml
service_url: !ENV ${MY_CUSTOM_SERVICE_URL}
```

I would prefer not to specify any default variables. This way, every user is free to extend his configuration with specific environment variables according to his needs.
