### ISSUE TITLE
Size of requested images from wms exceeds wms limits

### ISSUE THREAD

**Issue by michmuel** [openoereb/oereb_client#495]
It can happen that the oereb client requests an image from the wms that exceeds the size limit of the wms (when using a large screen). In that case the Mapserver returns an xml error message (http code 200) and the oereb_server returns an error. The map is not displayed by the client.

There should be an option for specifying the maximum size of a requested image.

**Comment by kdeininger** [comment]
I think this is a performance issue that should be handled by the backend. As an alternative, a tiled WMS can be used.
